version: "3"
services:
  mongo:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "0.0.0.0:27017:27017"

  web:
    container_name: web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile2
    ports:
      - "0.0.0.0:4200:4200"
    links:
      - mongo
    depends_on:
      - mongo
      - teamapp

  teamapp:
    container_name: webapp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/final_602
    ports:
      - "0.0.0.0:5000:5000"
    links:
      - mongo
    depends_on:
      - mongo
